---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c)
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /es
            pathType: Prefix
            backend:
              service:
                name: service-es
                port:
                  number: 9001
          - path: /en
            pathType: Prefix
            backend:
              service:
                name: service-default
                port:
                  number: 9001
