---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c)
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-es
  labels:
    app: frontend-es
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-es
  template:
    metadata:
      labels:
        app: frontend-es
    spec:
      containers:
        - name: server-es
          image: localhost/electrocucaracha/web:1.0
          env:
            - name: LOCALE
              value: es
---
apiVersion: v1
kind: Service
metadata:
  name: service-es
  labels:
    app: frontend-es
spec:
  type: ClusterIP
  ports:
    - port: 9001
      targetPort: 3000
  selector:
    app: frontend-es
